source 'https://rubygems.org'
gem 'rack'
gem 'siteleaf'
gem 'guard-sass'
gem 'guard-livereload'
gem 'guard-concat'
gem 'terminal-notifier'
gem 'terminal-notifier-guard'
gem 'rubyzip', :require => 'zip/zip'